### ISSUE TITLE
Core-js dependency problem

### ISSUE THREAD

**Issue by belkinbelkin** [microsoft/powerbi-visuals-circlecard-react#4]
Hi all, I tried to run the example app, but it failed to run with an exception - babel could not find several modules of core-js, because by default after npm i the app pulled some 2.x.x version.
To run the app, I found an appropriate version of core-js which resolved the issue and added it to package.json explicitely:
"core-js": "^3.6.4"
This way it worked smoothly.

**Comment by savnik** [comment]
Same issue - same solution..

**Comment by helen508light** [comment]
Pull request that fixes this issue is on review now
https://github.com/microsoft/powerbi-visuals-circlecard-react/pull/5/files
